name: .NET Build

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      working-directory: ./
      run: dotnet build --configuration Release
